import React from 'react';
import Head from 'next/head';
import Card from '@components/Card';
import fs from 'fs';
import matter from 'gray-matter';
import CategoriesList from '@utils/categories';
import Link from 'next/link';
import Navbar from '@components/Navbar';
import Footer from '@components/Footer';

import styles from '@styles/Home.module.css';

const CategoryPost = ({ articles }) => {
  const [loading, setLoading] = React.useState(true);
  const [listArticles, setListArticles] = React.useState(Array);

  const getCategoryOfPage = () => {
    const arrayOfCategories = CategoriesList();
    let URLactual = window.location.pathname;
    let categoria = '';
    for (var i in arrayOfCategories){
      if (URLactual.includes(arrayOfCategories[i])) {
        // setCategoryId(arrayOfCategories[i]); 
        categoria = arrayOfCategories[i];
        break;
      }
    }
    return categoria;
  }
  const getArrayOfArticles = () => {
    const categoriesArticles = [];
    const categoria = getCategoryOfPage();
    for (var i in articles) {
      if (articles[i].categories.includes(categoria)) {
        categoriesArticles.push(articles[i])
      }
    }
    setListArticles(categoriesArticles)
    return categoriesArticles;
  }

  function searchCategories() {
    if (articles.length > 0) {
      // console.log("data: ", listArticles)
      if (getArrayOfArticles() != []) {
        if (listArticles != null){
          // console.log(listArticles);
          console.log("data normal: ", listArticles)
          setLoading(false);
        } else {
          console.log("Error: retry... ",listArticles);
          const arr = getArrayOfArticles();
          setListArticles(arr);
          console.log("data retry: ", listArticles)
          setLoading(false);
        }
      } else {
        console.log("Esto es decepcionante...")
      }
    } else {
      console.log("Not articles")
    }
  }

  React.useEffect(() => {
    searchCategories();
  }, [])

  return (
    loading 
    ? 
    <div>LOADING...</div>
    :
    <div className={styles.container}>
      <Head>
        <title>McCoders blog | tecnologia y más</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.HeaderContainer}>
        <Navbar />
        <div className={styles.HeaderText}>
          <h1>McCoders Blog</h1>
          <p className={styles.HedTxt}>Este es un blog enfocado en tecnología.</p>
          {/* <p className={styles.Button}>Button</p> */}
          <div className={styles.Button}>
            <Link href="#">
              <a>Button</a>
            </Link>
          </div>
        </div>
      </header>
      <main>
        <div className={styles.PostsContainer}>
          {
            listArticles.map((article, i) => (
                <Card key={i} article={article} />
            ))
          }
        </div>
      </main>
      <Footer />
    </div>
  );
};

export const getStaticPaths = async () => {

  return {
      paths: [], //indicates that no page needs be created at build time
      fallback: 'blocking' //indicates the type of fallback
  }
}

export async function getStaticProps() {
  const files = fs.readdirSync("posts");
  
  let articles = files.map(file => {
      const data = fs
          .readFileSync(`posts/${file}`)
          .toString();

      return {
          ...matter(data).data,
          slug: file.split('.')[0]
      };
  });

  return {
      props: {
          articles: articles
      }
  };
}

export default CategoryPost;